### ISSUE TITLE
Push a new release to puppetforge

### ISSUE THREAD

**Issue by codesplicer** [claranet/puppet-consul_template#17]
Right now the puppetforge release for this module is outdated, from Jan 2015. Could you push a new release to forge please.

Thanks

**Comment by gdhbashton** [comment]
That's funny, I was reminding myself how that works just moments ago.. Expect something real soon...

**Comment by gdhbashton** [comment]
Cool, 0.2.0 now pushed to the Forge - thanks for the reminder :)
