### ISSUE TITLE
Feature request: consul_template::watch should take a variables hash

### ISSUE THREAD

**Issue by madAndroid** [claranet/puppet-consul_template#22]
Hi,

Firstly, great module :)
A feature request: would you consider adding a `variables` hash to the `consul_template::watch` define?
This would allow the (puppet) templating of the (consul) template more appropriately; for example to be able to use the same template for multiple `consul_template::watch` instances.

If you think this would be a good addition, I'll put a PR together

Thanks,
Andrew

**Comment by gdhbashton** [comment]
Hey Andrew - always good to hear from you!

Re-use is almost always desirable so yes I'd love to see a PR to improve `watch` :)

**Comment by madAndroid** [comment]
Hey Gavin :) awesome, I'll put something together... cheers! :)

**Comment by madAndroid** [comment]
Fixed with #23
