### ISSUE TITLE
User & group params are missing

### ISSUE THREAD

**Issue by chrisboulton** [claranet/puppet-consul_template#28]
#1 looks like it removed the class params that define the user/group consul-template should run as.

There's several references to `$consul_template::user` and `$consul_template::group` params throughout the manifests (Debian init script, resources for managing the user/group if `manage_user`/`manage_group` is defined)

This kind of also means there's some parity issues between different operating systems with different init scripts (at least, on Debian it was going to try and start/stop consul-template as a different user)

Personally, I haven't had time to look into addressing this yet but just wanted to make the issue known.

**Comment by gdhbashton** [comment]
Closed by PR #25
