### ISSUE TITLE
Updating a template does not restart consul-template daemon

### ISSUE THREAD

**Issue by madAndroid** [claranet/puppet-consul_template#29]
I'm not sure whether this is expected behaviour or not, but when I update a template that consul-template is using, using `consul_template::watch`, I expect the`consul-template` daemon be restarted, and this does not currently appear to be happening.

**Comment by nhandler** [comment]
See https://github.com/gdhbashton/puppet-consul_template/pull/26

**Comment by madAndroid** [comment]
ahhh... yes indeed - sorry, should probably search the issue tracker properly before logging an issue
