### ISSUE TITLE
Tarball-based installation does not update to new version

### ISSUE THREAD

**Issue by igorwwwwwwwwwwwwwwwwwwww** [claranet/puppet-consul_template#32]
Because this line does not detect a changed url, it will not update if the tarball exists on the local filesystem:

```
    staging::file { 'consul-template.tar.gz':
      source => $consul_template::download_url
    } ->
```

I suspect that adding the version number to the filename will solve this issue.

**Comment by gdhbashton** [comment]
Yep confirmed. I've just updated the default consul version in the module to 0.10.0 - and the release cadence of consul-template has slowed to near zero, so I'm not going to spend time on this one. PR's welcome as always.
