### ISSUE TITLE
Tags / releases in Github

### ISSUE THREAD

**Issue by madAndroid** [claranet/puppet-consul_template#35]
Awesome module, thanks for the hard work :)

Request: would it be possible to periodically cut a tag / release at what could be regarded as a stable point? we're pinning most of our modules to known good versions, and this is one of the few that we're 'pinning' to `origin/master` which is obviously a moving target ;) there was an issue that arose a short while back (I forget exactly what) and we ended up pinning to the shasum (5459841426444272b29034479900ce4ea46aa742, if it makes any difference), and although that's okay, it's not ideal. Thanks in advance! :)

**Comment by gdhbashton** [comment]
Hey Andrew,

I have been publishing versions to the Forge (tho not frequently) - there'll be another one soon once some .tar.gz / .zip changes for 0.11.0 from #34 are in master :)

**Comment by madAndroid** [comment]
Awesome, thanks Gavin :) We're mostly using tags in git repos, although we also pin to forge module versions - I'll look out for the next release. When you create a version in the Forge, do you also create a tag/release here in github? I'm assuming not, since there don't appear to be any listed currently, although there is a version in the Forge - that's where the confusion came in, it seems. Not a problem - will pin to the next version in the Forge, or to a sha-sum in GH if there's a newer change required that's not yet been released in the Forge.

**Comment by gdhbashton** [comment]
0.2.1 published on the Forge.
