### ISSUE TITLE
Switch from using concat to a native type

### ISSUE THREAD

**Issue by jaxxstorm** [claranet/puppet-consul_template#64]
Adding additional options, like SSL support, is a bit of a pain for this module because it doesn't support JSON configuration with a proper type.

I'd like to suggest that something like puppet-consul's [sorted json provider](https://github.com/solarkennedy/puppet-consul/blob/master/lib/puppet/parser/functions/consul_sorted_json.rb) is made use of, to better allow passing configuration options

**Comment by jaxxstorm** [comment]
I've started writing support for this in a fork. It's quite a significant overhaul, so if you're wanting to keep this module as is, I'll maintain it as a fork

**Comment by jaxxstorm** [comment]
I've _sort_ of finished this on my fork, here: https://github.com/jaxxstorm/puppet-consul_template

I haven't submitted a PR yet, because it's a major change and will probably break most people's existing setups.

If you're still interested, I'm happy to submit one, but I think it will be a semver major update.

**Comment by gdhbashton** [comment]
Hi there,

Thank you, that all looks very exciting :) I'm not quite ready to bump the major version or implement breaking changes right now (it's in use on many of our own setups at least) but I'll certainly be reading through the changes for the future :)

**Comment by jaxxstorm** [comment]
Thanks!

I'm going to close this, because I think I've made too many changes for it to ever be merged upstream, so I'm going to maintain it as a fork. Thanks for doing all the hard work of the base config!
