### ISSUE TITLE
Does this module support Puppet 4?

### ISSUE THREAD

**Issue by brahama** [claranet/puppet-consul_template#77]
Hi!

I've seen dependencies for nanliu/staging and that particular module does not support puppet 4. Anyone has tried it?

Thanks!

**Comment by lord2800** [comment]
It seems to work with puppet 4, but I use the `package` method of installation.

**Comment by craigwatson** [comment]
Hi @brahama,

The module _should_ work with Puppet 4 - I have just changed the module dependency for staging over to the voxpupuli fork and that does definitely support Puppet 4.

Thanks,
Craig
