### ISSUE TITLE
consul template doesn't die with systemd

### ISSUE THREAD

**Issue by jarro2783** [claranet/puppet-consul_template#83]
I think the latest version of consul template changed its default kill signal. From the docs:

    // This is the signal to listen for to trigger a graceful stop. The default
    // value is shown below. Setting this value to the empty string will cause CT
    // to not listen for any graceful stop signals.
    kill_signal = "SIGINT"

It seems like SIGTERM is ignored, which systemd tries to send when stopping the consul template service, and then sends SIGKILL 90 seconds later to kill it.

Can the puppet module either change the default or change the kill signal in the systemd unit file?

**Comment by sts** [comment]
+1 this causes a long delay before consul-template stops or restarts. Adding `kill_signal = "SIGTERM"` to `config.json` resolves this issue. 

This could be made configurable and the once configured value can be specified both in `config.json` as well as the systemd service template eg.: `KillSignal=SIGTERM`
https://www.freedesktop.org/software/systemd/man/systemd.kill.html#

**Comment by craigwatson** [comment]
Apologies for the delay here, this has been fixed in #94.
