### ISSUE TITLE
releases are not published on puppet forge

### ISSUE THREAD

**Issue by hex2a** [claranet/puppet-consul_template#92]
It seems like releases are not uploaded to puppet forge, and the project is still under the previous namespace: https://forge.puppet.com/gdhbashton/consul_template

**Comment by bastelfreak** [comment]
Hi.
I'm one of the [Vox Pupuli](https://voxpupuli.org/) maintainers. We developed a lot of community tools to make releases and all related tasks easier. We also adopt abandoned modules. Let us know if you need any help for automated releases. We're 24/7 in the IRC channel #voxpupuli on freenode.

**Comment by craigwatson** [comment]
HI @hex2a and @bastelfreak - thanks for raising this, we're going through a re-branding at the moment, as well as attempting to get through PRs and Issues when time permits.

Rest assured that we will be releasing new versions in due course :)
