### ISSUE TITLE
puppetlabs-concat dependency version causes issues

### ISSUE THREAD

**Issue by madAndroid** [claranet/puppet-consul_template#93]
We're experiencing this when using `librarian-puppet`:
- Since there's no upper limit to the version (it only specifies `>= 1.1.0`), there are dependency resolution issues when another module sets `>= 1.1.0 <3.0.0`

**Comment by madAndroid** [comment]
We have a workaround for this for now, but it would be good to set this as a range regardless

**Comment by bmhkb4** [comment]
Is this the error I'm getting here when trying to use 0.2.9?

`Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Puppet::Parser::AST::Resource failed with error ArgumentError: Invalid resource type concat::fragment at /etc/puppet/modules/consul_template/manifests/config.pp:17 on node <node>`

**Comment by craigwatson** [comment]
@madAndroid - Apologies for the delay in getting to look at this, I've added proper bounds to the dependencies in `metadata.json` - what was your original issue?

@bmhkb4 - Your issue sounds like you don't have the `concat` module installed. I'd check this first, and raise a separate issue here if you do.
