### ISSUE TITLE
Service.pp not actioning hiera values properly

### ISSUE THREAD

**Issue by atatara** [claranet/puppet-consul_template#99]
While removing consul-service from chkconfig, I noticed that module is not taking proper action according to values set in hiera. This is fixed in the attached file with hiera lookup.
![screen shot 2017-08-28 at 17 55 56](https://user-images.githubusercontent.com/10167296/29781782-9ba88812-8c1a-11e7-8df9-9321fdf574f4.png)

**Comment by craigwatson** [comment]
Hi,

Thanks for raising this - your Hiera values should be passed into the main `consul_template` class, so there should be no need to modify the `service.pp` file directly.

For example, in Hiera:

```
consul_template::service_ensure: 'stopped'
consul_template::service_enable: false
```

Can you also confirm the version of Puppet you are using?

Thanks,
Craig

**Comment by craigwatson** [comment]
@atatara as this issue hasn't seen any activity in a couple of months, I'll close it for now. Please do feel free to re-open if the problem can't be solved using Hiera as I explained above.
